### ISSUE TITLE
Remove unused vhosts files

### ISSUE THREAD

**Issue by mtlynch** [mtlynch/ansible-role-nginx#1]
This has bitten me [two](https://github.com/mtlynch/tinypilot/pull/70) [times](https://github.com/mtlynch/ansible-role-tinypilot/pull/79), and I now recognize it as a bug in the Ansible role.

The [vhosts.yml](https://github.com/mtlynch/ansible-role-nginx/blob/9ae8584281c7f8f3897cbcdfdb682c8750641e36/tasks/vhosts.yml) playbook attempts to manage all the `.conf` files in the nginx vhosts path, but it fails to remove stale files. So if you use the nginx role to place a vhosts file called `foo.conf`, then update your configuration so that the file is now called `bar.conf`, nginx will place the new file but won't remove the old file.

What the role should do instead is:

1. Find all .conf files in `nginx_vhost_path ` and save them as `existing_vhost_files`
1. Go through each item in `nginx_vhosts` where `state` = `present` and save them as `managed_vhost_files`
1. Create a new list like `vhosts_to_remove` which is `existing_vhost_files - managed_vhost_files`
1. Change the removal logic to:

```yaml
- name: Remove unmanaged .conf files.
  file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ vhosts_to_remove }}"
  notify: reload nginx
```
